### ISSUE TITLE
全局搜索所使用的yolov5s，有考虑过采用更适用于小目标检测的改进算法或其他小目标检测模型进行替代吗，是否有可能获得更好的效果

### ISSUE THREAD

**Issue by duenyuduenyu** [WestlakeIntelligentRobotics/Global-Local-MAV-Detection#4]

**Comment by Irisky123** [comment]
感谢您的关注。我们的方法是即插即用的，全局搜索模块可以用更适用于小目标检测的算法替代，我们后面的文章也确实做了很多改进，会有更好的效果。

**Comment by duenyuduenyu** [comment]
> 感谢您的关注。我们的方法是即插即用的，全局搜索模块可以用更适用于小目标检测的算法替代，我们后面的文章也确实做了很多改进，会有更好的效果。

请问后面的文章目前有发表或者在github上公开源码吗，想继续学习一下。

**Comment by duenyuduenyu** [comment]
> 

另外，所谓的即插即用，就是指在全局搜索和局部搜索的部分可以将yolo代替吗，也就是tensorrt推理engine模型的部分可以用其他模型进行替代

**Comment by Irisky123** [comment]
是的，YOLO完全是可以替代的。我这里为了加速运算和方便部署，使用了tensorrt版本的YOLO。但是也完全可以调用Python版本的。其他的检测模型比如R-CNN系列，SDD等也完全可以嵌入。后面的文章还在发表中，应该在年内会公开代码。

**Comment by duenyuduenyu** [comment]
好的，十分感谢，另外还想问一下权重文件夹下的动态链接库libmyplugins.so的主要作用是什么呢

**Comment by Irisky123** [comment]
你看一下tensorrt的编译就知道了，调用tensorrt时候用到的一个链接库。
